In [1]:
import numpy as np

# np.cumsum

In [2]:
# cumsum은 배열에서 주어진 축에 따라 누적되는 원소들의 누적 합을 계산하는 함수
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
print(np.cumsum(a))
# 각 원소들의 누적 합을 표시함. 각 row와 column의 구분은 없어지고, 순서대로 sum을 함.
# 1  /  1+2  /  1+2+3  / 1+2+3+4  /  1+2+3+4+5  / 1+2+3+4+5+6

[ 1  3  6 10 15 21]


In [5]:
print(np.cumsum(a, dtype = float))
# 결과 값의 변수 type을 설정하면서 누적 sum을 함.

[ 1.  3.  6. 10. 15. 21.]


In [8]:
print(a)
print()
print(np.cumsum(a, axis = 0))
# axis = 0은 같은 column 끼리의 누적 합을 함.

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [5 7 9]]


In [10]:
print(a)
print()
print(np.cumsum(a, axis = 1))
# axis = 1은 같은 row끼리의 누적 합을 함.

[[1 2 3]
 [4 5 6]]

[[ 1  3  6]
 [ 4  9 15]]
