##### SVM(Support Vector Machine)
---
- ML에서 오랫동안 연구되었고 성능이 좋은 모델
- DL보다 성능이 좋은 경우도 있음

In [65]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

In [66]:
# Logistic

from sklearn.linear_model import LogisticRegression

In [67]:
data, target = load_digits(return_X_y=True)

In [68]:
data_train, data_test, target_train, target_test = \
    train_test_split(data, target, random_state=42)

In [69]:
data_train.shape, data_test.shape

((1347, 64), (450, 64))

In [70]:
model_lr = LogisticRegression(max_iter=2500)
model_lr.fit(data_train, target_train)

LogisticRegression(max_iter=2500)

In [71]:
# 학습 후 설정된 속성
print('분류 종류 : ', model_lr.classes_)
print('가중치 값 : ', model_lr.coef_)
print('절편 값 : ', model_lr.intercept_)
print('특성 갯수 : ', model_lr.n_features_in_)

분류 종류 :  [0 1 2 3 4 5 6 7 8 9]
가중치 값 :  [[ 0.00000000e+00 -6.63197945e-03 -1.17751800e-02  6.15844775e-02
   2.11605873e-02 -7.65460911e-02 -1.32679331e-01 -3.07657990e-02
  -1.03673418e-06 -6.53924406e-02 -1.70196032e-02  1.48349763e-01
   4.82190404e-03  4.41342633e-02 -6.34132631e-02 -2.82243270e-02
  -1.88377843e-03  9.29786047e-03  7.29552574e-02 -5.15025981e-02
  -3.42163559e-01  1.46745096e-01  1.07115354e-02 -7.24986482e-03
  -9.41893483e-04  1.02387889e-01  1.38013607e-01 -9.48891173e-02
  -4.17295698e-01  5.30405408e-02  6.37366745e-02 -5.95525522e-06
   0.00000000e+00  1.25206390e-01  4.42494271e-02 -1.04135757e-01
  -3.40213823e-01  3.02396424e-02  5.23085079e-02  0.00000000e+00
  -1.05504204e-05 -5.67502529e-02  2.55901567e-01 -1.75323323e-01
  -1.59043308e-01  9.58114731e-02  2.48853995e-02 -1.43698544e-06
  -4.31091500e-05 -1.16264217e-01  1.47086558e-01 -9.83258175e-02
   1.56677507e-01  1.64801864e-02 -2.43180916e-02 -9.94768328e-03
   1.91604822e-08 -7.33213364e-03 -6

In [72]:
print('train score :', model_lr.score(data_train, target_train))
print('test score :', model_lr.score(data_test, target_test))

train score : 1.0
test score : 0.9733333333333334


In [73]:
ret = model_lr.decision_function([data_test[0]])
print(np.round(ret,3))

[[ 3.827 -2.785 -9.152 -8.612 -0.115 -4.208 20.435 -4.194  9.41  -4.606]]


In [74]:
from scipy.special import softmax, expit
sigValue2 = softmax(ret)
print(np.round(sigValue2,3))

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [75]:
# SVC
from sklearn.svm import SVC

In [76]:
model_svc = SVC(gamma=0.001)

In [77]:
model_svc.fit(data_train, target_train)

SVC(gamma=0.001)

In [78]:
# 학습 후 설정된 속성
print('분류 종류 : ', model_svc.classes_)
print('절편 값 : ', model_svc.intercept_)
print('특성 갯수 : ', model_svc.n_features_in_)

분류 종류 :  [0 1 2 3 4 5 6 7 8 9]
절편 값 :  [-0.48327398 -0.41558392 -0.33531727 -0.4261569  -0.47857456 -0.23253434
 -0.39337247 -0.45767357 -0.44869516  0.15000623  0.2627687   0.11105631
  0.08715567  0.35812658  0.06800405  0.18948837  0.1372283   0.10351618
 -0.01924294 -0.02382352  0.24661372 -0.05656143 -0.02604761 -0.02813988
 -0.13428613 -0.11873549  0.11229116 -0.1748401  -0.16127873 -0.12177897
  0.03892034  0.29690992  0.00999124 -0.00868364 -0.03513616  0.28502202
 -0.01003341  0.04927633 -0.12962626 -0.22523473 -0.33246807 -0.2669999
  0.07352291 -0.00913735 -0.12550687]
특성 갯수 :  64


In [79]:
print('train score :', model_svc.score(data_train, target_train))
print('test score :', model_svc.score(data_test, target_test))

train score : 0.9977728285077951
test score : 0.9888888888888889


In [80]:
# 결정함수 y = wx + b
ret = model_svc.decision_function([data_test[0]])
print(np.round(ret,3))

[[ 2.803  5.899  0.757  1.748  3.833  5.885  9.304 -0.258  8.24   5.886]]


In [81]:
sigValue2 = softmax(ret)
print(np.round(sigValue2,3))

[[0.001 0.023 0.    0.    0.003 0.023 0.69  0.    0.238 0.023]]
