In [211]:
# 모듈 로딩(1)
import json
import pandas as pd
import os
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
from collections import Counter

In [212]:
# 모듈 로딩(2)
from tensorflow.keras.utils import set_random_seed, plot_model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPool2D
from tensorflow.keras.datasets.fashion_mnist import load_data
import matplotlib.pyplot as plt

In [213]:
df = pd.read_csv('./bus_getonoff_sum.csv')
# df

***

In [214]:
df['get_num'].value_counts()

2    626429
0    225248
1    131447
Name: get_num, dtype: int64

***

In [215]:
df['action_num'].value_counts()
# 약 90만개의 데이터가 있음

3    486990
1    279102
0    108011
5     99613
4      4799
7      2641
2      1631
6       337
Name: action_num, dtype: int64

In [216]:
df1 = pd.read_csv('./bus_state.csv')

In [217]:
df1['action_num'].value_counts()

3    14756
0     9412
1     8111
4     4718
5     3791
7     2641
6      327
2      150
Name: action_num, dtype: int64

In [218]:
# 6k 10
# 2r 1100 (x)
# 0st, 1w, 3s d, 5g h 다
# 4l d ,7p =
# ===== 
# 6(kick)은 그다지 늘어나지 않음
# 2(run)은 그렇게 많지는 않을 것임
# 4(lay down)과 7(punch)는 거의 변동x
# 0(stand), 1(walk), 3(sit down), 5(grab handle)은 많이 늘어남
# 효용이 있을지는 모르겠으나 일단 ㄱ

In [219]:
df.head()

bbox                                          keypoints  \
0   [974, 266, 1471, 1077]  [1074, 1020, 2, 1111, 923, 2, 1151, 752, 2, 12...   
1  [1017, 224, 1452, 1060]  [1094, 918, 2, 1131, 802, 2, 1185, 643, 2, 131...   
2  [1007, 224, 1445, 1049]  [1085, 909, 2, 1118, 787, 2, 1174, 634, 2, 129...   
3  [1007, 222, 1428, 1049]  [1082, 908, 2, 1113, 786, 2, 1155, 627, 2, 127...   
4   [995, 220, 1421, 1044]  [1071, 904, 2, 1102, 782, 2, 1144, 623, 2, 127...   

  action  get_on  get_off  get_num  action_num  
0  stand    True    False        1           0  
1  stand    True    False        1           0  
2  stand    True    False        1           0  
3  stand    True    False        1           0  
4  stand    True    False        1           0

In [220]:
df['keypoints']

0         [1074, 1020, 2, 1111, 923, 2, 1151, 752, 2, 12...
1         [1094, 918, 2, 1131, 802, 2, 1185, 643, 2, 131...
2         [1085, 909, 2, 1118, 787, 2, 1174, 634, 2, 129...
3         [1082, 908, 2, 1113, 786, 2, 1155, 627, 2, 127...
4         [1071, 904, 2, 1102, 782, 2, 1144, 623, 2, 127...
                                ...                        
983119    [997, 1077, 0, 997, 1010, 0, 1016, 1042, 0, 88...
983120    [1458, 636, 1, 1483, 581, 1, 1494, 658, 1, 141...
983121    [1446, 632, 1, 1471, 577, 1, 1482, 654, 1, 139...
983122    [1373, 670, 1, 1372, 585, 1, 1418, 523, 2, 133...
983123    [1331, 670, 1, 1337, 561, 1, 1381, 437, 1, 129...
Name: keypoints, Length: 983124, dtype: object

In [221]:
# 열 타입변경
# keypoints와 bbox는 문자열 값으로 저장되어 있어서 배열 형태로 바꾸어 주어야 할 필요성이 있어보여서 이 코드를 만듬
keypoins_arr=[]
bbox_arr=[]

for i in range(len(df)): # 테이블 행 수 만큼 for문 돌림
    bbox_arr.append(np.array(list(map(int,df.bbox[i].strip('[').strip(']').split(','))))) 
    keypoins_arr.append(np.array(list(map(int,df.keypoints[i].strip('[').strip(']').split(',')))))
    
# 배열 형태로 값들이 저장됨
df.bbox=bbox_arr
df.keypoints=keypoins_arr


In [222]:
keypoints = np.array(list(df.keypoints)).reshape(-1,16,3,1)

In [223]:
type(df.keypoints)

pandas.core.series.Series

In [224]:
keypoints.shape

(983124, 16, 1, 3)

In [225]:
# 'action_num'을 배열로만 넘겨주면 되겠지
y = np.array(df.action_num)
y.shape

(983124,)

In [226]:
# train과 test 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(keypoints, y, test_size=0.2, random_state=42)

In [227]:
import tensorflow as tf

In [244]:
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam,SGD,RMSprop,Adagrad
from tensorflow.keras.callbacks import EarlyStopping
from keras.layers import Dropout, Flatten,Activation, BatchNormalization
from keras.layers import Conv2D, MaxPooling2D, Conv3D, MaxPool2D

***

***

***

In [205]:
# model=Sequential()
# 이미지 특징 추출 Layer => 첫번째 입력값 설정
model.add(Conv2D(10, kernel_size=3, padding='same', input_shape=(28,28,1)))

# Conv와 MaxPool2D는 한 세트로 생각하고 바로 입력
# 이미지 특징 다운샘플링 layer => MaxPool2D

# 더이상 한 세트를 실행하지 않겠다 => 출력전 1차원으로 펴줘야 함
# 1차원으로 데이터 형태 변환 Layer => Flatten
model.add(Flatten())

# 결과 출력층 => Node : 0-9까지 10개, activation : softmax
model.add(Dense(10, activation='softmax'))

# 아웃풋으로 보는 것
model.summary()
# (None, 28, 28, 1)에서 None은 -1이라고 생각하면 됨 <= 몇 개 들어올지 모름
# 피처는 786개인데
# 왜 Param #이 10 ?
# -> 커널 한개 특징맵 1개
# -> 커널에는 가중치가 들어 있음 (3x3+1) => 10개 (1개는 bias)

# 커널마다 특징맵에 2개가 되니까, 커널을 2개로 바꾸면
# => (None, 28, 28, 1) -> (None, 28, 28, 2)

# pedding = 'same'을 없애면
# (None, 28, 28, 2) -> (None, 26, 26, 2)

# MaxPool2D -> 연산x, 가로세로 줄어듦 : (28->14)

# 과정 시각화 (인풋도 볼 수 있즤)
# plot_model(model, show_shapes=True, to_file='CNN.png')


***

In [229]:
model=Sequential()
model.add(Conv2D(30, kernel_size=3, padding='same', input_shape=(16, 3, 1))) 
# 이미지 특징 다운샘플링 Layer => MaxPool2D
# 1차원으로 데이터 형태 변환 Layer => Flatten
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(8, activation='softmax')) # 1차원

In [ ]:
model = Sequential()

model.add(Conv2D(input_shape = (X_train.shape[1], X_train.shape[2], X_train.shape[3]), filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

In [245]:
# 2D 
model = Sequential()
model.add(Conv2D(32, kernel_size=3, activation='relu', kernel_initializer='he_uniform', input_shape=(16,3,1)))
model.add(MaxPooling2D(pool_size=2,padding='same'))
model.add(BatchNormalization(center=True, scale=True))
model.add(Dropout(0.5))
# model.add(Conv2D(64, kernel_size=3, activation='relu', kernel_initializer='he_uniform'))
# model.add(MaxPooling2D(pool_size=2,padding='same'))
# model.add(BatchNormalization(center=True, scale=True))
# model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(256, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(256, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(8, activation='softmax'))

# 여기요 여기예요
---

In [253]:
# CNN2d
model = Sequential()          
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal', input_shape=(16,3,1)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(filters = 50, kernel_size = (3,3), strides = (1,1), padding = 'same', kernel_initializer='he_normal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Flatten())

# dense layer with 50 neurons
model.add(Dense(50, activation = 'relu', kernel_initializer='he_normal'))
model.add(Dropout(0.5))

# final layer with 8 neurons to classify the instances
model.add(Dense(8, activation='softmax'))

# model 컴파일
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(lr=0.001),
              metrics=['accuracy'])

# print(model.summary())


***

In [251]:
# prior layer should be flattend to be connected to dense layers
model.add(Flatten())

# dense layer with 50 neurons
model.add(Dense(50, activation = 'relu', kernel_initializer='he_normal'))
model.add(Dropout(0.5))

# final layer with 10 neurons to classify the instances
model.add(Dense(10, activation = 'softmax', kernel_initializer='he_normal'))

# model 컴파일
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(lr=0.001),
              metrics=['accuracy'])

# adam = optimizers.Adam(lr = 0.001)
# model.compile(loss = 'categorical_crossentropy', optimizer = adam, metrics = ['accuracy'])


C:\Users\ahasu\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [254]:
with tf.device("/device:GPU:0"):
    # model.fit(X_train, y_train, epochs=10)
    model.fit(x_train, y_train, validation_split=0.2, epochs=20)

Epoch 1/20


ValueError: in user code:

    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 296, in assert_input_compatibility
        f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_19" is incompatible with the layer: expected shape=(None, 16, 3, 1), found shape=(None, 16, 1, 3)


In [ ]:
# callbacks
es=EarlyStopping(monitor='val_accuracy',patience=10)
mc=ModelCheckpoint('model.h5',monitor='val_accuracy',save_best_only=True)

# 모델훈련
history = model.fit(x_train, y_train,
            batch_size=128,
            epochs=1000,
            verbose=1,
            validation_data=(x_val,y_val),
            callbacks=[es,mc])

***

In [ ]:
# 2D 
model = Sequential()
model.add(Conv2D(32, kernel_size=3, activation='relu', kernel_initializer='he_uniform', input_shape=(16,3,1)))
model.add(MaxPooling2D(pool_size=2,padding='same'))
model.add(BatchNormalization(center=True, scale=True))
model.add(Dropout(0.5))
# model.add(Conv2D(64, kernel_size=3, activation='relu', kernel_initializer='he_uniform'))
# model.add(MaxPooling2D(pool_size=2,padding='same'))
# model.add(BatchNormalization(center=True, scale=True))
# model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(256, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(256, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(8, activation='softmax'))

# callbacks
es=EarlyStopping(monitor='val_accuracy',patience=10)
mc=ModelCheckpoint('model.h5',monitor='val_accuracy',save_best_only=True)

# 모델 컴파일
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(lr=0.001),
              metrics=['accuracy'])
model.summary()

# 모델훈련
history = model.fit(x_train, y_train,
            batch_size=128,
            epochs=1000,
            verbose=1,
            validation_data=(x_val,y_val),
            callbacks=[es,mc])

***

In [207]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=8)

In [208]:
model.compile(loss='categorical_crossentropy',
              optimizer = 'adam', metrics='accuracy')

***

In [230]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer = 'adam', metrics='accuracy')

In [151]:
y_train

array([0, 5, 5, ..., 1, 3, 1], dtype=int64)

In [209]:
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15433314001887705777
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3646947328
locality {
  bus_id: 1
  links {
  }
}
incarnation: 9405054585743190922
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]
Num GPUs Available:  1


In [233]:
with tf.device("/device:GPU:0"):
    # model.fit(X_train, y_train, epochs=10)
    model.fit(x_train, y_train, validation_split=0.2, epochs=20)

Epoch 1/20
19663/19663 [==============================] - 64s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2347 - val_accuracy: 0.4952
Epoch 2/20
19663/19663 [==============================] - 62s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2346 - val_accuracy: 0.4952
Epoch 3/20
19663/19663 [==============================] - 62s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2346 - val_accuracy: 0.4952
Epoch 4/20
19663/19663 [==============================] - 64s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2346 - val_accuracy: 0.4952
Epoch 5/20
19663/19663 [==============================] - 64s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2346 - val_accuracy: 0.4952
Epoch 6/20
19663/19663 [==============================] - 64s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1.2346 - val_accuracy: 0.4952
Epoch 7/20
19663/19663 [==============================] - 65s 3ms/step - loss: 1.2351 - accuracy: 0.4955 - val_loss: 1

In [159]:
model.fit(x_train, y_train, validation_split=0.2, epochs=20)

Epoch 1/20


ValueError: in user code:

    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 994, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\training.py", line 1053, in compute_loss
        y, y_pred, sample_weight, regularization_losses=self.losses
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\losses.py", line 272, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\losses.py", line 1991, in categorical_crossentropy
        y_true, y_pred, from_logits=from_logits, axis=axis
    File "C:\Users\ahasu\anaconda3\lib\site-packages\keras\backend.py", line 5529, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 8) are incompatible


In [89]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(get, num_classes=3)

In [90]:
y.shape

(16493, 3)

# 연습

In [94]:
# stand = 0
# walk = 1
# run = 2
# sit down = 3
# laydown = 4
# grab handle = 5
# kick = 6
# violence = 7

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
result = le.fit_transform(df[''])
print(result)

i) 라벨(y)를 'action'컬럼을 라벨인코딩해서 배열로 넘기는 것

In [86]:
label = df['action']
label.unique()

array(['stand', 'walk', 'sit down', 'run', 'grab handle', 'lay down',
       'kick', 'punch'], dtype=object)

In [95]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(["stand", "walk", "run", "sit down", "lay down", "grab handle", "kick", "violence"])
le.classes_

array(['grab handle', 'kick', 'lay down', 'run', 'sit down', 'stand',
       'violence', 'walk'], dtype='<U11')

In [88]:
le

LabelEncoder()

In [89]:
le.fit(label)

LabelEncoder()

In [90]:
label_encoded = le.transform(label)
label_encoded

array([6, 6, 6, ..., 5, 6, 6])

In [91]:
type(label_encoded)

numpy.ndarray

In [92]:
type(label)

pandas.core.series.Series

In [93]:
l_e_df = pd.DataFrame(label_encoded, columns=['label_encoded'])
pd.concat([label, l_e_df], axis=1)

action  label_encoded
0          stand              6
1          stand              6
2          stand              6
3          stand              6
4          stand              6
...          ...            ...
983119      walk              7
983120  sit down              5
983121  sit down              5
983122     stand              6
983123     stand              6

[983124 rows x 2 columns]

In [68]:

le.fit(["stand", "walk", "run", "sit down", "lay down", "grab handle", "kick", "violence"])

LabelEncoder()

In [69]:
le.classes_

array(['grab handle', 'kick', 'lay down', 'run', 'sit down', 'stand',
       'violence', 'walk'], dtype='<U11')

In [70]:
le.transform(["stand", "walk", "run", "sit down", "lay down", "grab handle", "kick", "violence"])

array([5, 7, 3, 4, 2, 0, 1, 6])

In [ ]:
>>> from sklearn import preprocessing
>>> le = preprocessing.LabelEncoder()
>>> le.fit([1, 2, 2, 6])
LabelEncoder()

>>> le.classes_
array([1, 2, 6])

>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2])

>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])

In [67]:
le = preprocessing.LabelEncoder()
le.fit(["stand", "walk", "run", "sit down", "lay down", "grab handle", "kick", "violence"])
LabelEncoder()
list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
# le.transform(["tokyo", "tokyo", "paris"])
# array([2, 2, 1])
# list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']

NameError: name 'LabelEncoder' is not defined

In [ ]:
stand = 0
walk = 1
run = 2
sit down = 3
laydown = 4
grab handle = 5
kick = 6
violence = 7

In [33]:
keypoints = df['keypoints']

In [38]:
keypoints = np.array(keypoints)

In [37]:
keypoints

array(['[1074, 1020, 2, 1111, 923, 2, 1151, 752, 2, 1266, 829, 2, 1180, 1012, 2, 1371, 1077, 0, 1193, 798, 2, 1248, 643, 2, 1334, 462, 2, 1320, 342, 2, 1102, 736, 2, 1148, 649, 2, 1225, 456, 2, 1442, 563, 2, 1407, 763, 2, 1334, 889, 2]',
       '[1094, 918, 2, 1131, 802, 2, 1185, 643, 2, 1311, 694, 2, 1234, 873, 2, 1189, 979, 2, 1233, 687, 2, 1288, 559, 2, 1357, 382, 2, 1357, 303, 2, 1121, 634, 2, 1178, 542, 2, 1232, 392, 2, 1418, 454, 2, 1400, 604, 2, 1344, 700, 2]',
       '[1085, 909, 2, 1118, 787, 2, 1174, 634, 2, 1291, 684, 2, 1214, 862, 2, 1187, 967, 2, 1226, 678, 2, 1281, 542, 2, 1345, 377, 2, 1334, 302, 2, 1100, 624, 2, 1158, 543, 2, 1230, 389, 2, 1415, 450, 2, 1392, 599, 2, 1336, 693, 2]',
       ...,
       '[1446, 632, 1, 1471, 577, 1, 1482, 654, 1, 1399, 654, 1, 1249, 594, 2, 1233, 682, 2, 1437, 654, 1, 1402, 504, 2, 1385, 410, 2, 1379, 345, 2, 1438, 566, 1, 1512, 543, 1, 1480, 432, 2, 1333, 424, 1, 1268, 454, 1, 1298, 368, 1]',
       '[1373, 670, 1, 1372, 585, 1, 1418, 52