In [90]:
import numpy as np

In [91]:
# 1차원 & array
a = np.arange(1,9)
print(a, type(a))

[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [92]:
# 행은 개수 알아서 맞춰주고, 열은 2개로 하기
a = a.reshape(-1,2)
print(a, type(a))

[[1 2]
 [3 4]
 [5 6]
 [7 8]] <class 'numpy.ndarray'>


In [93]:
# 2차원 & 리스트
aa = [[1,2],[3,4],[5,6]]
print(aa, type(aa))

[[1, 2], [3, 4], [5, 6]] <class 'list'>


In [94]:
# 2차원 & 리스트 -> 2차원 & array
aa = np.array(aa)
print(aa, type(aa))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [95]:
# 2차원 & array -> 3차원 & array
aa = np.array(aa, ndmin=3)
print(aa, type(aa))

[[[1 2]
  [3 4]
  [5 6]]] <class 'numpy.ndarray'>


In [96]:
# 1차원 & 리스트
b = [1,2,3,4,5,6,7,8,9]
print(b, type(b))

[1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [97]:
# 1차원 & 리스트 -> 3차원 & array
b = np.array(b, ndmin=3)
print(b, type(b))

[[[1 2 3 4 5 6 7 8 9]]] <class 'numpy.ndarray'>


In [98]:
# 0으로 차원 초기화 (실수로)
a = np.zeros(shape=(3,5), dtype=float)
print(a, type(a))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'>


In [99]:
# 0으로 차원 초기화 (정수로)
a = np.zeros(shape=(3,5), dtype=int)
print(a, type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [100]:
# 3차원 & array -> 3차원 & list로
print(aa, type(aa))
print()
aa = aa.tolist()
print(aa, type(aa))

[[[1 2]
  [3 4]
  [5 6]]] <class 'numpy.ndarray'>

[[[1, 2], [3, 4], [5, 6]]] <class 'list'>
