In [4]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
 
np.save('./saved_x', x)

[[1 2]
 [3 4]]


In [25]:
A1 = np.zeros(6)
A2 = np.zeros((2,3))
A3 = np.zeros((2,3), dtype = np.int64, order = 'C')
B1= np.ones((2,3))
B2= np.zeros((5,5))
C1 = np.full((3,2), 10, dtype = np.int32)
C2 = np.empty((3,2))
D1 = np.full((2,3), 10, dtype = np.int32)

print(F'A1:{A1}\n')
print(F'A2:{A2}\n')
print(F'A3:{A3}\n')
print(F'B1:{B1}\n')
print(F'B2:{B2}\n')
print(F'C1:{C1}\n')
print(F'C2:{C2}\n')
print(F'D1:{D1}\n')

A1:[0. 0. 0. 0. 0. 0.]

A2:[[0. 0. 0.]
 [0. 0. 0.]]

A3:[[0 0 0]
 [0 0 0]]

B1:[[1. 1. 1.]
 [1. 1. 1.]]

B2:[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

C1:[[10 10]
 [10 10]
 [10 10]]

C2:[[1. 1.]
 [1. 1.]
 [1. 1.]]

D1:[[10 10 10]
 [10 10 10]]



In [28]:
print('abd','der','skskeojh','329iefjkdlas',sep='!', end='END!!!')

abd!der!skskeojh!329iefjkdlasEND!!!